server:
  port: 8761
#开启用户认证
spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka8761.com
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: true #表示是否从eureka server获取注册信息
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka8761.com:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka8762.com:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka8763.com:8763/eureka/
    healthcheck: true #开启健康检查，这里检查的注册服务的健康信息