server:
  port: 8761
eureka:
  instance:
    hostname: eureka8761.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #表示自己端就是注册中心，职责是维护实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/
