server:
  port: 8001
spring:
  application:
    name: test-cloud-provider
  security:
    user:
      name: admin
      password: 123456
eureka:
  client:
    service-url:
      #defauleZone: http://admin:1q2w3e4r@localhost:8761/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka8761.com:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka8762.com:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka8763.com:8763/eureka/

  instance:
    instance-id: test-cloud-provider8001
    prefer-ip-address: true

#需要引入actuator
info:
  app.name: testCloudProvider
  company.name: www.annie.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
